### ISSUE TITLE
why do you use SQS

### ISSUE THREAD

**Issue by HoangNgo88** [robinrodricks/FluentStorage#7]
Hi, I am reading your project and I love this project
I have a question, why do you choose SQS in your project instead of others like RabbitMQ or Kafka, are there any special features but others dont have it. Can you share me it. I am wondering when I should choose SQS instead of others like RabbitMQ or Kafka

**Comment by robinrodricks** [comment]
I don't make any design choices. FluentStorage aims to support ALL providers of blob/queue storage.

So yes we would like to add RabbitMQ and Kafka.

If you are asking why people choose SQS the answer is its the native messaging tech on AWS cloud solutions. If you don't build AWS solutions you don't need it.

**Comment by robinrodricks** [comment]
Intros:

- RabbitMQ - https://www.youtube.com/watch?v=NQ3fZtyXji0
- SQS - https://www.youtube.com/watch?v=CyYZ3adwboc

Here are a few factors to help you decide which one to go for:

1. RabbitMQ is FIFO by default. Amazon SQS queues can optionally be set to FIFO.

2. You can setup your own server with RabbitMQ but not in the case of Amazon SQS so the cost gets involved here.

3. Setting up your own server will require good knowledge of the subject so that you do not leave any corner untouched. This is not the case with Amazon SQS as it is pretty quick to get started with.

4. Your own RabbitMQ server means maintenance cost down the line which is not the case with Amazon SQS.
